collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7957394
  brandStrength: 0
  rhythmicContrast: 0.3007519
  brandColors:
    - '#1E7EF6'
    - '#F8FFFF'
    - '#C6D3E2'
    - '#7AB5F4'
    - '#96DBFF'
  lightness: 0.8270677
typography_spectrum: 0.566927
layout_spectrum: 0.5075188
name: serenebi
