layout_spectrum: 0.5651629
color:
  saturation: 0.7957394
  lightness: 0.8270677
  brandStrength: 0.6240602
  brandColors:
    - '#FFFFFF'
    - '#050304'
    - '#C2BCA4'
    - '#3E2719'
    - '#AB8A7F'
  rhythmicContrast: 0.3007519
typography_spectrum: 0.566927
name: serenebi
