collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.566927
color:
  saturation: 0.7957394
  brandStrength: 0
  rhythmicContrast: 0.3007519
  brandColors:
    - '#FFFFFF'
    - '#050304'
    - '#C2BCA4'
    - '#3E2719'
    - '#AB8A7F'
  lightness: 0.8270677
layout_spectrum: 0
name: serenebi
